"""Initial Migration

Revision ID: c34f024727e6
Revises: 
Create Date: 2025-04-29 17:31:25.743062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34f024727e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Insert initial data into the product table
    op.bulk_insert(
        sa.table(
            'product',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('price', sa.Float),
            sa.column('description', sa.String)
        ),
        [
            {'id': 1, 'name': 'Laptop', 'price': 999.99, 'description': 'A high-performance laptop'},
            {'id': 2, 'name': 'Smartphone', 'price': 699.99, 'description': 'A latest model smartphone'},
            {'id': 3, 'name': 'Headphones', 'price': 199.99, 'description': 'Noise-cancelling headphones'},
            {'id': 4, 'name': 'Monitor', 'price': 299.99, 'description': '4K Ultra HD monitor'},
            {'id': 5, 'name': 'Keyboard', 'price': 49.99, 'description': 'Mechanical keyboard'}
        ]
    )

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('login')
    # ### end Alembic commands ###
